src/Entity/Agence.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\AgenceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=AgenceRepository::class)
 */
class Agence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="date")
     */
    private $startedAt;

    /**
     * @ORM\Column(type="date")
     */
    private $endingAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $link_picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address_street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_street2;

    /**
     * @ORM\Column(type="integer")
     */
    private $address_zip_postal;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $address_town;

    /**
     * @ORM\OneToMany(targetEntity=Adherent::class, mappedBy="agence", fetch="EAGER", orphanRemoval=true)
     */
    private $adherents;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="agence", fetch="EAGER")
     */
    private $users;

    /**
     * @ORM\ManyToMany(targetEntity=Agence::class, inversedBy="droit_agence", fetch="EAGER")
     */
    private $droit_agence;

    public function __construct()
    {
        $this->adherents = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->droit_agence = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->startedAt;
    }

    public function setStartedAt(\DateTimeInterface $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getEndingAt(): ?\DateTimeInterface
    {
        return $this->endingAt;
    }

    public function setEndingAt(\DateTimeInterface $endingAt): self
    {
        $this->endingAt = $endingAt;

        return $this;
    }

    public function getLinkPicture()
    {
        return $this->link_picture;
    }

    public function setLinkPicture($link_picture): self
    {
        $this->link_picture = $link_picture;

        return $this;
    }

    public function getAddressStreet(): ?string
    {
        return $this->address_street;
    }

    public function setAddressStreet(string $address_street): self
    {
        $this->address_street = $address_street;

        return $this;
    }

    public function getAddressStreet2(): ?string
    {
        return $this->address_street2;
    }

    public function setAddressStreet2(?string $address_street2): self
    {
        $this->address_street2 = $address_street2;

        return $this;
    }

    public function getAddressZipPostal(): ?int
    {
        return $this->address_zip_postal;
    }

    public function setAddressZipPostal(int $address_zip_postal): self
    {
        $this->address_zip_postal = $address_zip_postal;

        return $this;
    }

    public function getAddressTown(): ?string
    {
        return $this->address_town;
    }

    public function setAddressTown(string $address_town): self
    {
        $this->address_town = $address_town;

        return $this;
    }

    /**
     * @return Collection|Adherent[]
     */
    public function getAdherents(): Collection
    {
        return $this->adherents;
    }

    public function addAdherent(Adherent $adherent): self
    {
        if (!$this->adherents->contains($adherent)) {
            $this->adherents[] = $adherent;
            $adherent->setAgence($this);
        }

        return $this;
    }

    public function removeAdherent(Adherent $adherent): self
    {
        if ($this->adherents->removeElement($adherent)) {
            // set the owning side to null (unless already changed)
            if ($adherent->getAgence() === $this) {
                $adherent->setAgence(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addAgence($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeAgence($this);
        }

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getDroitAgence(): Collection
    {
        return $this->droit_agence;
    }

    public function addDroitAgence(self $droitAgence): self
    {
        if (!$this->droit_agence->contains($droitAgence)) {
            $this->droit_agence[] = $droitAgence;
        }

        return $this;
    }

    public function removeDroitAgence(self $droitAgence): self
    {
        $this->droit_agence->removeElement($droitAgence);

        return $this;
    }
}

src/Entity/Meet.php
<?php

namespace App\Entity;

use App\Repository\MeetRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=MeetRepository::class)
 */
class Meet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Adherent::class, inversedBy="adherent_woman")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $adherent_woman;

    /**
     * @ORM\ManyToOne(targetEntity=Adherent::class, inversedBy="adherent_man")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $adherent_man;
    
    /**
     * @ORM\Column(type="date")
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $startedAt;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $returnAt_woman;

    /**
     * @ORM\Column(type="date", nullable=true)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $returnAt_man;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $comments_woman;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("adherent:read")
     * @Groups("meet:read")
     */
    private $comments_man;

    /**
     * @ORM\ManyToOne(targetEntity=AdherentOption::class, inversedBy="status_meet_woman")
     * @Groups("meet:read")
     */
    private $status_meet_woman;

    /**
     * @ORM\ManyToOne(targetEntity=AdherentOption::class, inversedBy="status_meet_man")
     * @Groups("meet:read")
     */
    private $status_meet_man;

    /**
     * @ORM\ManyToOne(targetEntity=AdherentOption::class, inversedBy="meets")
     * @Groups("meet:read")
     */
    private $actionMeetWoman;

    /**
     * @ORM\ManyToOne(targetEntity=AdherentOption::class, inversedBy="meets")
     * @Groups("meet:read")
     */
    private $actionMeetMan;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->startedAt;
    }

    public function setStartedAt(\DateTimeInterface $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getReturnAtWoman(): ?\DateTimeInterface
    {
        return $this->returnAt_woman;
    }

    public function setReturnAtWoman(?\DateTimeInterface $returnAt_woman): self
    {
        $this->returnAt_woman = $returnAt_woman;

        return $this;
    }

    public function getReturnAtMan(): ?\DateTimeInterface
    {
        return $this->returnAt_man;
    }

    public function setReturnAtMan(?\DateTimeInterface $returnAt_man): self
    {
        $this->returnAt_man = $returnAt_man;

        return $this;
    }

    public function getCommentsWoman(): ?string
    {
        return $this->comments_woman;
    }

    public function setCommentsWoman(?string $comments_woman): self
    {
        $this->comments_woman = $comments_woman;

        return $this;
    }

    public function getCommentsMan(): ?string
    {
        return $this->comments_man;
    }

    public function setCommentsMan(?string $comments_man): self
    {
        $this->comments_man = $comments_man;

        return $this;
    }

    public function getStatusMeetWoman(): ?AdherentOption
    {
        return $this->status_meet_woman;
    }

    public function setStatusMeetWoman(?AdherentOption $status_meet_woman): self
    {
        $this->status_meet_woman = $status_meet_woman;

        return $this;
    }

    public function getStatusMeetMan(): ?AdherentOption
    {
        return $this->status_meet_man;
    }

    public function setStatusMeetMan(?AdherentOption $status_meet_man): self
    {
        $this->status_meet_man = $status_meet_man;

        return $this;
    }

    public function getAdherentWoman(): ?Adherent
    {
        return $this->adherent_woman;
    }

    public function setAdherentWoman(?Adherent $adherent_woman): self
    {
        $this->adherent_woman = $adherent_woman;

        return $this;
    }

    public function getAdherentMan(): ?Adherent
    {
        return $this->adherent_man;
    }

    public function setAdherentMan(?Adherent $adherent_man): self
    {
        $this->adherent_man = $adherent_man;

        return $this;
    }

    public function getActionMeetWoman(): ?AdherentOption
    {
        return $this->actionMeetWoman;
    }

    public function setActionMeetWoman(?AdherentOption $actionMeetWoman): self
    {
        $this->actionMeetWoman = $actionMeetWoman;

        return $this;
    }

    public function getActionMeetMan(): ?AdherentOption
    {
        return $this->actionMeetMan;
    }

    public function setActionMeetMan(?AdherentOption $actionMeetMan): self
    {
        $this->actionMeetMan = $actionMeetMan;

        return $this;
    }
}

templates/file/pdfTest.html.twig
<p>1</p>
<img src="{{ image1 }}" alt="">
<p>2</p>
<img src="{{ image2 }}" alt="">
<p>3</p>
<img src="{{ image3 }}" alt="">
<p>4</p>
<img src="{{ image4 }}" alt="">
<p>5</p>
<img src="{{ image5 }}" alt="">

templates/file/pdfTestimony.html.twig
<style>
    .logo-agence{
        width: 150px;
    }

    .info-adherent{
        text-align: right;
    }

    .post-scriptum{
        text-align: right;
        font-size: 0.8rem;
    }

    .testimony-title{
        text-transform: uppercase;
        text-align: center;
    }

    .testimony{
        border: 1px solid black;
        height: 30%;
        padding-right: 3rem;

    }

    .date-sign{
        text-align: right;
        padding-top: 13rem;
    }

</style>
<img class="logo-agence" src="{{ image }}" alt="Image"/>
<p class="info-adherent">
    {{ adherent.lastname }} {{ adherent.firstname }}<br/>
    {{ adherent.addressStreet }}<br/>
    {{ adherent.addressZipPostal }} {{ adherent.addressTown }}
</p>
<p>{{ adherent.firstname }},</p>

<p>Je suis très heureux d'apprendre que vous êtes en relation avec une qui nous a fait confiance, qui a fait la même démarche que vous.<br/>
Maintenant, vous savez, vous aussi, qu'il est possible de rencontrer le bonheur grâce aux services de votre conseiller {{ adherent.agence.name }}<br/>
Afin de rassurer d'autres personnes et ainsi leur permettre de faire cette démarche en tout confiance.<br/>
Je vous proposer de me raconter, à l'aide de ce document, votre démarche, votre rencontre ...</p>

<p>Il est bien entendu que je respecterai votre anonymat, et que seul votre témoignage (sans nom ni adresse) pourra être mis à la disposition de nouveaux adhérents.</p>

<p>Je vous remercie très sincèrement pour votre contribution au bonheur d'autres personnes.</p>

<p>J'attends votre courrier !</p>

<p>Bien Cordialement, Votre conseiller.</p>

<p class="post-scriptum">PS: merci de renvoyer cette feuille sans la découper.</p>

<p class="testimony-title">Témoignage</p>

<div class="testimony">
    <p class="date-sign">Date et signature</p>
</div>

templates/file/pdfView.html.twig
<style>
    body{
        min-height: 29.7cm;
    }

    h1{
        color:red;
    }

    h2{
        font-size: 1.2rem;
    }

    p{
        font-size: 0.8rem;
    }

    .img-logo{
        width: 150px;
    }

    .adherent-left{
        display: inline-block;
        width: 80%;
        height: 2%;
    }

    .adherent-right{
        display: inline-block;
        width: 20%;
        font-size: 1rem;
        height: 2%;
    }

    .info-meet-name{
        color: #86133d;
    }

    .info-meet-age{
        margin-left: 20.2%;
    }

    .info-meet-phone{
        margin-left: 7.6%;
    }

    .info-meet-agence{
        margin-left: 17.3%;
    }

    span{
        margin: 0 2rem;
    }

    .info-meet-all{
        display: inline-block;
        margin-left: 45%;
        font-style: italic;
    }

    .title-information{
        font-style: italic;
        font-weight: bold;
        font-size: 1rem;
    }

    .title-result-meet{
        text-align: center;
        color: #86133d;
    }

    .text-positive,
    .text-negative{
        width: 100%;
        height: 1%;
        border-bottom: 1px solid black;
    }

    .choice-right{
        text-align: right;
    }


    .choice-adherent{
        border: 2px solid #86133d;
        padding: 6px;
    }

    .sign-adherent{
        text-align: right;
    }

    .message-footer{
        text-transform: uppercase;
    }

    footer{
        position: fixed;
        text-align: center;
        bottom: 3rem;
    }

</style>
<body>
    <img class='img-logo' src="{{ image }}" alt="Logo">

    <div class="adherent-info">
        <div class="adherent-left">
{#            <p>Le {{ date|date('d/m/Y') }}</p>#}
            <p>Réf. {{ idMeet }}</p>
        </div>
        <p class="adherent-right">
            {{ adherent.lastname }} {{ adherent.firstname }}<br/>
            {{ adherent.addressStreet }}<br/>
            {{ adherent.addressZipPostal }} {{ adherent.addressTown }}
        </p>
    </div>
    <div class="">
        <p class="info-meet-name">Nom de la personne sélectionné<span>:</span>{{ meetAdherent.firstname }} {{ meetAdherent.lastname }}</p>
        <p class="info-meet-age">Âge<span>:</span>{{ meetAdherent.getAge() }}</p>
        <p class="info-meet-phone">Numéro de téléphone<span>:</span>{{ meetAdherent.phoneMobile }}</p>
        <p class="info-meet-agence">Agence <span>:</span>{{ meetAdherent.agence.name }}</p>
    </div>
    <div class="">
        <p class="info-meet-all">{{ meetAdherent.profession }}, {{ meetAdherent.statusMatrimoniale }}, {{ meetAdherent.size }}, Yeux: {{ meetAdherent.eyes }}, Cheveux: {{ meetAdherent.hair }}</p>
    </div>
    <div class="">
        <h2 class="title-information">Renseignements sur cette personne :</h2>
        <p>{{ meetAdherent.announcementPresentation| raw }}</p>
    </div>
    <div class="">
        <h2 class="title-result-meet">Résultat de la rencontre, vos commentaires :</h2>
        <h3>Points Positifs :</h3>
        <p class="text-positive"></p>
        <p class="text-positive"></p>
        <p class="text-positive"></p>
        <p class="text-positive"></p>
        <h3>Points Négatifs :</h3>
        <p class="text-negative"></p>
        <p class="text-negative"></p>
        <p class="text-negative"></p>
        <p class="text-negative"></p>
    </div>
    <div class="choice-left">
        <p><span class="choice-adherent"> </span>Je souhaite recevoir une nouvelle sélection</p>
        <p><span class="choice-adherent"> </span>Je souhaite que mon dossier soit mis en attente</p>
    </div>
    <div class="choice-right">
        <p class="sign-adherent">Date et signature de l'adhérent</p>
    </div>
    <footer>
        <p class="message-footer">Le retour de ce document est imperatif pour recevoir une nouvelle sélection</p>
        <p class="address-agence">{{ adherent.agence.name }} - {{ adherent.agence.addressStreet }} - {{ adherent.agence.addressZipPostal }} {{ adherent.agence.addressTown }} - {{ adherent.agence.email }}</p>
    </footer>
</body>

templates/file/template.csv.twig
id, status_matrimoniale_id, status_meet_id, instruction_id, lodging_id, smoking_id, hair_id, zodiaque_id, eyes_id, genre_id, preference_contact_id, search_instruction_id, firstname, lastname, birthdate, comments1, comments2, comments3, phone_mobile, phone_home, phone_work, phone_comments, profession, size, weight, permis, car, announcement_publish, announcement_presentation, announcement_free, announcement_date_free, announcement_newspaper, announcement_date_newspaper, email, link_picture, link_contract, link_information, link_picture_announcement, address_street, address_street2, address_zip_postal, address_town, child_girl, child_boy, child_dependent_girl, child_dependent_boy, search_age_min, search_age_max, search_single, search_divorced, search_widower, search_profession, search_region, search_more, search_accept_children, search_number_accept_children, owner_id, type_payment_id, contract_date, contract_started_at, contract_ending_at, contract_amount, contract_comments, agence_id,
{% for adherent in adherents %}
{% set i = (i | default(-1)) + 1 %}
{{ adherent.id }},{{ adherent.statusMatrimoniale }},{{ adherent.statusMeet }},{{ adherent.instruction }},{{ adherent.lodging }},{{ adherent.smoking }},{{ adherent.hair }},{{ adherent.zodiaque }},{{ adherent.eyes }},{{ adherent.genre }},{{ adherent.preferenceContact }},"{{ adherent.searchInstruction }}",{{ adherent.firstname }},{{ adherent.lastname }},{{ adherent.birthdate|date('d/m/Y') }},"{{ adherent.comments1 }}","{{ adherent.comments2 }}","{{ adherent.comments3 }}",{{ adherent.phoneMobile }},{{ adherent.phoneHome }},{{ adherent.phoneWork }},"{{ adherent.phoneComments }}","{{ adherent.profession }}",{{ adherent.size }},{{ adherent.weight }},{{ adherent.permis }},{{ adherent.car }},"{{ adherent.announcementPublish }}","{{ adherent.announcementPresentation| striptags }}","{{ adherent.announcementFree| striptags }}",{{ adherent.announcementDateFree|date('d/m/Y') }},"{{ adherent.announcementNewspaper| striptags }}",{{ adherent.announcementDateNewspaper|date('d/m/Y') }},{{ adherent.email }},"{{ adherent.linkPicture }}","{{ adherent.linkContract }}","{{ adherent.linkInformation }}","{{ adherent.linkPictureAnnouncement }}","{{ adherent.addressStreet }}","{{ adherent.addressStreet2 }}",{{ adherent.addressZipPostal }},{{ adherent.addressTown }},{{ adherent.childGirl }},{{ adherent.childBoy }},{{ adherent.childDependentGirl }},{{ adherent.childDependentBoy }},{{ adherent.searchAgeMin }},{{ adherent.searchAgeMax }},{{ adherent.searchSingle }},{{ adherent.searchDivorced }},{{ adherent.searchWidower }},"{{ adherent.searchProfession }}",{{ adherent.searchRegion }},"{{ adherent.searchMore }}",{{ adherent.searchAcceptChildren }},{{ adherent.searchNumberAcceptChildren }},{{ adherent.owner }},{{ adherent.typePayment }},{{ adherent.contractDate|date('d/m/Y') }},{{ adherent.contractStartedAt|date('d/m/Y') }},{{ adherent.contractEndingAt|date('d/m/Y') }},{{ adherent.contractAmount }},"{{ adherent.contractComments| striptags }}",{{ adherent.Agence }}
{% for meet in meets[i] %}
"", {{ meet.id }}, {{ meet.adherentWoman.lastname }} {{ meet.adherentWoman.firstname }}, {{ meet.adherentMan.lastname }} {{ meet.adherentMan.firstname }}, {{ meet.startedAt|date('d/m/Y') }}, {{ meet.returnAtWoman|date('m/d/Y') }}, {{ meet.returnAtMan|date('m/d/Y') }}, {{ meet.commentsWoman }}, {{ meet.commentsMan }}
{% endfor %}

{% endfor %}